#!/usr/bin/env bash
set -eu
export HEXFIELD_SUPPORT_RADIUS=4 HEXFIELD_SERVE_FLEX=1
export HEXFIELD_CHANNELS=192 HEXFIELD_ATTENTION_HEADS=3 HEXFIELD_TRUNK=CCACCACCACCACCA
export HEXFIELD_TRITON_CONV=1 HEXFIELD_FLEX_PAIR=1 HEXFIELD_TRITON_ATTN=1 HEXFIELD_TRITON_CONV_LN=1
/root/.venvs/hexgt-build/bin/python /mnt/e/Hexo-BotTrainer-hexgt/scripts/_main7_convln_unit.py
